
version: '3'

services:
  flask:
    build:
      context: ./casino-back
      dockerfile: Dockerfile
    image: flask
    container_name: flask
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "5000:5000"
  nodejs:
    build:
      context: ./casino-front
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "3000:3000"
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ssl-keys:/etc/letsencrypt/live/intergaming.com/
    depends_on:
      - nodejs
    networks:
      - app-network
volumes:
  ssl-keys:
    driver: local
    driver_opts:
      type: none
      device: /etc/letsencrypt/live/intergaming.com/
      o: bind
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /root/Full-casino/
      o: bind
networks:
  app-network:
    driver: bridge