
version: '3'

services:
  flask:
    build:
      context: ./casino-back
      dockerfile: Dockerfile
    image: flask
    container_name: flask
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "5000:5000"
  nodejs:
    build:
      context: ./casino-front
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "3000:3000"
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - nodejs
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email ivan.zubillaga@sistemasabstractos.com --agree-tos --no-eff-email --force-renewal -d sistemasabstractos.com.mx -d www.sistemasabstractos.com.mx
volumes:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/Full-casino/dhparam/
      o: bind
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /root/Full-casino/
      o: bind

networks:
  app-network:
    driver: bridge
